import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { sampleSize, lookupTable } from '../../skills/experiment-methodology/scripts/proportions.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const SCRIPT = path.join(ROOT, 'skills/experiment-methodology/scripts/proportions.mjs');

test('normal approximation matches the audit counterexamples after rounding up', () => {
  assert.equal(sampleSize({ baseline: 0.05, mde: 0.05 }).perVariant, 432);
  assert.equal(sampleSize({ baseline: 0.05, mde: 0.10 }).perVariant, 138);
  const result = sampleSize({ baseline: 0.05, mde: 0.05 });
  assert.ok(Math.abs(result.unrounded - 431.2) < 1e-9);
  assert.equal(result.alternative, 0.10);
  assert.equal(result.relativeMde, 1);
});

test('relative lift and percentage points are distinct inputs', () => {
  const relative = sampleSize({ baseline: 0.05, mde: 0.10, mdeType: 'relative' });
  assert.ok(Math.abs(relative.alternative - 0.055) < 1e-12);
  assert.equal(relative.perVariant, 31196);
  assert.equal(sampleSize({ baseline: 0.05, mde: 0.10, mdeType: 'absolute' }).perVariant, 138);
  assert.equal(sampleSize({ baseline: 0.05, mde: 0.005, mdeType: 'absolute' }).perVariant, relative.perVariant);
});

test('direction is explicit and reversing the same two probabilities preserves sample size', () => {
  assert.equal(sampleSize({ baseline: 0.10, mde: 0.05, direction: 'decrease' }).perVariant, 432);
  assert.ok(sampleSize({ baseline: 0.40, mde: 0.10, direction: 'decrease' }).perVariant
    !== sampleSize({ baseline: 0.40, mde: 0.10, direction: 'increase' }).perVariant);
});

test('rejects undefined, impossible and non-finite probability/effect inputs', () => {
  for (const baseline of [0, 1, -0.1, 2, NaN, Infinity, undefined]) {
    assert.throws(() => sampleSize({ baseline, mde: 0.01 }), RangeError);
  }
  for (const mde of [0, -0.01, NaN, Infinity, undefined]) {
    assert.throws(() => sampleSize({ baseline: 0.05, mde }), RangeError);
  }
  assert.throws(() => sampleSize({ baseline: 0.95, mde: 0.10 }), RangeError);
  assert.throws(() => sampleSize({ baseline: 0.05, mde: 0.05, direction: 'decrease' }), RangeError);
  assert.throws(() => sampleSize({ baseline: 0.05, mde: 0.01, direction: 'sideways' }), RangeError);
  assert.throws(() => sampleSize({ baseline: 0.05, mde: 0.01, mdeType: 'pp' }), RangeError);
});

test('the entire shipped lookup table is generated by the calculation source', () => {
  const reference = fs.readFileSync(path.join(ROOT, 'skills/experiment-methodology/references/proportions.md'), 'utf8');
  const table = reference.match(/^\| Baseline \|[\s\S]*?(?=\n\n)/m)?.[0];
  assert.equal(table, lookupTable());
});

test('optional CLI is portable across working directories and rejects invalid input', () => {
  const result = JSON.parse(execFileSync(process.execPath, [SCRIPT, '0.05', '0.05', 'absolute'], {
    cwd: os.tmpdir(), encoding: 'utf8',
  }));
  assert.equal(result.perVariant, 432);
  const failed = spawnSync(process.execPath, [SCRIPT, '0.95', '0.1'], { encoding: 'utf8' });
  assert.equal(failed.status, 1);
  assert.match(failed.stderr, /alternative/);
  assert.equal(failed.stdout, '');
});
